### ISSUE TITLE
Add support for akka typed

### ISSUE THREAD

**Issue by karolchmist** [ruippeixotog/akka-testkit-specs2#11]
With Akka 2.6, typed actors has become the new paradigm. Would be nice to add support for it in your project.

I can help if you would like to give me some hints to get started.

**Comment by ruippeixotog** [comment]
Thanks for the proposal, @karolchmist! I need to look at the API to see the best way to integrate it here.

**Comment by ruippeixotog** [comment]
b7079655b656f34fe8e66e810a0333f69a8a527f adds support for typed actors. I'm going to update the README and release a new version in the next few days.

**Comment by karolchmist** [comment]
Thank you!
